### ISSUE TITLE
Encoding HTML converts text to single line

### ISSUE THREAD

**Issue by ProLoser** [BrightIT/escape-utils#4]
Seems to destroy newline characters or something.

**Comment by PiotrCzapla** [comment]
Could you give me some examples? I've just encoded:
```
"line 1"
"line 2"
"line 3"
"line 4"
```

to
``` 
&quot;line 1&quot;&NewLine;&quot;line 2&quot;&NewLine;&quot;line 3&quot;&NewLine;&quot;line 4&quot; 
```

And decoded it back to the original text so the feature works as expected.

If you don't want the new lines to be encoded just split the selection to multiple  Shit-Mac-L and then do the encoding. It will leave the new lines untouched.

Here is what I've get for the example above:
```
&quot;line 1&quot;
&quot;line 2&quot;
&quot;line 3&quot;
&quot;line 4&quot;
```

**Comment by ProLoser** [comment]
Ahhh... That seems like unusual behavior that you should opt-into vs out of.

**Comment by PiotrCzapla** [comment]
it is consistent with other encodings. and it is quite useful for: base64 for example. I rather keep this consistent, but feel free to add a configuration option to turn this off.
