### ISSUE TITLE
Odd Encoding Quotes

### ISSUE THREAD

**Issue by djmtype** [BrightIT/escape-utils#8]
Not sure if this issue has to due with Atom itself as I tried AbeEstrada's [atom-html-entities](https://github.com/AbeEstrada/atom-html-entities) and it encoded quotes oddly, too. For example, a right single quote, produced `&CloseCurlyQuote;` instead of `&rsquo;` 

Encoding the right single quote use to output `&rsquo;` before. 
My syntax is set to HTML, UTF-8. Atom v1.3.2

**Comment by PiotrCzapla** [comment]
The plugin is not smart enough to use the syntax it just uses one of the libraries shipped with atom that does the encoding. I think both encoding are the same when you render them in the browser so it is hard to tell which one is the correct one.

I agree that `&rsqua;` is more natural than `&CloseCurlyQuote;`, but for some reason the library we are using have different defaults.

I will think about getting xml encoding implemented, hopefully it will use better encoding.
